-- v15追加SQL：担当者プルダウン用テーブル
-- Supabase SQL Editorで1回実行してください

create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.staff_members enable row level security;

drop policy if exists "staff read all" on public.staff_members;
drop policy if exists "staff insert all" on public.staff_members;
drop policy if exists "staff delete all" on public.staff_members;

create policy "staff read all"
on public.staff_members
for select
using (true);

create policy "staff insert all"
on public.staff_members
for insert
with check (true);

create policy "staff delete all"
on public.staff_members
for delete
using (true);

insert into public.staff_members (name)
values ('田中')
on conflict (name) do nothing;
