-- v5追加SQL：在庫チェック履歴用テーブル
-- Supabase SQL Editorで一度だけ実行してください

create table if not exists public.inventory_checks (
  id bigint generated by default as identity primary key,
  checked_at timestamptz not null default now(),
  barcode text not null references public.products(barcode) on update cascade,
  product_name text not null,
  checked_by text not null,
  stock_at_check integer not null default 0,
  memo text default ''
);

alter table public.inventory_checks enable row level security;

drop policy if exists "checks read all" on public.inventory_checks;
drop policy if exists "checks insert all" on public.inventory_checks;

create policy "checks read all" on public.inventory_checks for select using (true);
create policy "checks insert all" on public.inventory_checks for insert with check (true);
