-- Supabase SQL Editorで実行してください

create table if not exists public.products (
  barcode text primary key,
  name text not null,
  base_stock integer not null default 0,
  location text default '',
  created_at timestamptz not null default now()
);

create table if not exists public.inventory_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null check (type in ('入荷','出荷','在庫修正')),
  staff text not null,
  barcode text not null references public.products(barcode) on update cascade,
  product_name text not null,
  quantity integer not null,
  memo text default ''
);

alter table public.products enable row level security;
alter table public.inventory_logs enable row level security;

drop policy if exists "products read all" on public.products;
drop policy if exists "products insert all" on public.products;
drop policy if exists "products update all" on public.products;
drop policy if exists "logs read all" on public.inventory_logs;
drop policy if exists "logs insert all" on public.inventory_logs;

create policy "products read all" on public.products for select using (true);
create policy "products insert all" on public.products for insert with check (true);
create policy "products update all" on public.products for update using (true) with check (true);

create policy "logs read all" on public.inventory_logs for select using (true);
create policy "logs insert all" on public.inventory_logs for insert with check (true);
